#!/usr/bin/env python3
"""Build assets/glb_embedded.js from GLB files (offline file:// slide demos)."""

from __future__ import annotations

import base64
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ASSETS_DIR = REPO_ROOT / "assets"
OUT_FILE = ASSETS_DIR / "glb_embedded.js"


def main() -> int:
    glb_files = sorted(ASSETS_DIR.glob("*.glb"))
    if not glb_files:
        print(f"No GLB files in {ASSETS_DIR}", file=sys.stderr)
        return 1

    lines = [
        "// Auto-generated by scripts/generate-glb-embeds.py",
        "window.__EMBED_GLB__ = {",
    ]
    for glb in glb_files:
        data = base64.b64encode(glb.read_bytes()).decode("ascii")
        lines.append(f'  "{glb.name}": "{data}",')
    lines.append("};")

    OUT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    size_kb = OUT_FILE.stat().st_size / 1024
    print(f"Wrote {OUT_FILE} ({size_kb:.1f} KB, {len(glb_files)} GLB file(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
